version: 2

updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "America/Chicago"
    groups:
      elixir-dependencies:
        applies-to: version-updates
        update-types: ["minor", "patch"]
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "America/Chicago"
    groups:
      all-actions:
        patterns:
          - "*"
